from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Text, Boolean, JSON, UniqueConstraint, Index
from sqlalchemy.orm import relationship
from datetime import datetime
from app.db.database import Base

class District(Base):
    __tablename__ = "districts"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), unique=True, nullable=False, index=True)
    province = Column(String(50), nullable=False, index=True)
    centroid_lat = Column(Float)
    centroid_lon = Column(Float)
    elevation_mean = Column(Float)
    elevation_min = Column(Float)
    elevation_max = Column(Float)
    slope_mean = Column(Float)
    area_km2 = Column(Float)
    rainfall_annual_mm = Column(Float)
    rainfall_cv = Column(Float)
    temp_mean_c = Column(Float)
    temp_min_c = Column(Float)
    temp_max_c = Column(Float)
    humidity_pct = Column(Float)
    sunshine_hours_annual = Column(Float)
    soil_type = Column(String(50))
    soil_ph = Column(Float)
    soil_organic_matter = Column(Float)
    soil_nitrogen = Column(Float)
    ndvi_mean = Column(Float)
    ndvi_trend = Column(Float)
    ndvi_std = Column(Float)
    flood_risk_score = Column(Float)
    drought_risk_score = Column(Float)
    soil_degradation_score = Column(Float)
    avg_maize_yield = Column(Float)
    avg_potato_yield = Column(Float)
    avg_bean_yield = Column(Float)
    avg_coffee_yield = Column(Float)
    avg_tea_yield = Column(Float)
    coffee_suitable = Column(Boolean, default=False)
    tea_suitable = Column(Boolean, default=False)
    banana_suitable = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    crop_trials = relationship("CropTrial", back_populates="district", cascade="all, delete-orphan")
    predictions = relationship("Prediction", back_populates="district", cascade="all, delete-orphan")
    climate_records = relationship("ClimateRecord", back_populates="district", cascade="all, delete-orphan")
    forecasts = relationship("ClimateForecast", back_populates="district", cascade="all, delete-orphan")

class CropTrial(Base):
    __tablename__ = "crop_trials"
    id = Column(Integer, primary_key=True, index=True)
    district_id = Column(Integer, ForeignKey("districts.id", ondelete="CASCADE"), nullable=False)
    crop = Column(String(50), nullable=False)
    variety = Column(String(100), nullable=False)
    season = Column(String(20))
    year = Column(Integer)
    soil_ph_trial = Column(Float)
    rainfall_season_mm = Column(Float)
    temp_mean_trial = Column(Float)
    humidity_trial = Column(Float)
    ndvi_at_planting = Column(Float)
    irrigation = Column(String(20), default="rainfed")
    fertilizer = Column(String(100))
    yield_t_ha = Column(Float)
    performance_score = Column(Float)
    disease_incidence = Column(Float)
    notes = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    district = relationship("District", back_populates="crop_trials")

class Prediction(Base):
    __tablename__ = "predictions"
    id = Column(Integer, primary_key=True, index=True)
    district_id = Column(Integer, ForeignKey("districts.id", ondelete="CASCADE"), nullable=False)
    crop = Column(String(50))
    variety = Column(String(100))
    suitability_score = Column(Float)
    yield_prediction_t_ha = Column(Float)
    risk_level = Column(String(20))
    confidence = Column(Float)
    shap_values_json = Column(JSON)
    recommendation = Column(Text)
    model_version = Column(String(20), default="2.0.0")
    created_at = Column(DateTime, default=datetime.utcnow)
    district = relationship("District", back_populates="predictions")

class ClimateRecord(Base):
    __tablename__ = "climate_records"
    id = Column(Integer, primary_key=True, index=True)
    district_id = Column(Integer, ForeignKey("districts.id", ondelete="CASCADE"), nullable=False)
    year = Column(Integer, nullable=False)
    month = Column(Integer, nullable=False)
    rainfall_mm = Column(Float)
    temp_mean_c = Column(Float)
    temp_max_c = Column(Float)
    temp_min_c = Column(Float)
    humidity_pct = Column(Float)
    ndvi = Column(Float)
    sunshine_hours = Column(Float)
    drought_score = Column(Float)
    heat_stress_score = Column(Float)
    flood_risk_score = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)
    district = relationship("District", back_populates="climate_records")
    __table_args__ = (UniqueConstraint("district_id", "year", "month", name="uq_climate_district_month"),)

class ClimateForecast(Base):
    __tablename__ = "climate_forecasts"
    id = Column(Integer, primary_key=True, index=True)
    district_id = Column(Integer, ForeignKey("districts.id", ondelete="CASCADE"), nullable=False)
    forecast_for_year = Column(Integer)
    forecast_for_month = Column(Integer)
    predicted_rainfall_mm = Column(Float)
    predicted_temp_mean_c = Column(Float)
    drought_probability = Column(Float)
    flood_probability = Column(Float)
    crop_failure_probability = Column(Float)
    harvest_quality_score = Column(Float)
    model_used = Column(String(50))
    confidence_interval_low = Column(Float)
    confidence_interval_high = Column(Float)
    created_at = Column(DateTime, default=datetime.utcnow)
    district = relationship("District", back_populates="forecasts")

class SimilarityCache(Base):
    __tablename__ = "similarity_cache"
    id = Column(Integer, primary_key=True, index=True)
    district_a_id = Column(Integer, ForeignKey("districts.id"))
    district_b_id = Column(Integer, ForeignKey("districts.id"))
    similarity_score = Column(Float)
    method = Column(String(30), default="cosine")
    feature_set = Column(String(50), default="full_v2")
    computed_at = Column(DateTime, default=datetime.utcnow)
